# https://taskfile.dev

version: '3'

vars:
  KARPENTER_NAMESPACE: "kube-system"
  KARPENTER_VERSION: "1.5.0"
  K8S_VERSION: "1.32"
  CLUSTER_NAME: "karpenter-demo"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_PARTITION: "aws" # if you are not using standard partitions, you may need to configure to aws-cn / aws-us-gov



tasks:
  default:
    cmds:
      - tofu init -upgrade
      - tofu plan -out out.plan
      - tofu apply "out.plan"
    silent: true

  destroy:
    cmds:
      - tofu destroy -auto-approve
